name: Terraform Provisioning (VPC, EC2, S3, ECR, etc.)

on:
    push:
        branches:
            - main

    workflow dispatch:

jobs:
    terraform-provisioning:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-north-1

            - name: Initialize Terraform
              run: terraform init

            - name: Plan terraform changes
              run: terraform plan

            - name: Apply terraform changes
              run: terraform apply --auto-approve
